services:
  - type: web
    name: apple-tv-bot
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y wget unzip curl gnupg2

      # Install Chrome
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable

      # Get Chrome version and install matching ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
      echo "Chrome version: $CHROME_VERSION"

      # Install ChromeDriver using chromium-chromedriver package
      apt-get install -y chromium-chromedriver
      ln -s /usr/lib/chromium/chromedriver /usr/local/bin/chromedriver
      chmod +x /usr/local/bin/chromedriver

      # Verify installations
      echo "Chrome version:"
      google-chrome --version
      echo "ChromeDriver version:"
      chromedriver --version

      # Create directory for Chrome
      mkdir -p /tmp/.chrome
      chmod 777 /tmp/.chrome

      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
      - key: PATH
        value: "/usr/local/bin:/usr/lib/chromium:/usr/bin:${PATH}"
      - key: TMPDIR
        value: "/tmp"
      - key: CHROME_USER_DATA_DIR
        value: "/tmp/.chrome"
    healthCheckPath: /health
    autoDeploy: true 