services:
  - type: web
    name: apple-tv-bot
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y wget unzip curl gnupg2

      # Install Chrome
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable

      # Get Chrome version and install matching ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
      CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d "." -f1)
      echo "Chrome version: $CHROME_VERSION"
      echo "Chrome major version: $CHROME_MAJOR_VERSION"

      # Download and install ChromeDriver directly
      wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}" -O chromedriver_version.txt
      CHROMEDRIVER_VERSION=$(cat chromedriver_version.txt)
      echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
      wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip -q chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      rm chromedriver_linux64.zip chromedriver_version.txt

      # Verify installations
      echo "Chrome version:"
      google-chrome --version
      echo "ChromeDriver version:"
      chromedriver --version

      # Create directory for Chrome
      mkdir -p /tmp/.chrome
      chmod 777 /tmp/.chrome

      # Install Python dependencies
      pip install -r requirements.txt
      
      # Create log directory
      mkdir -p /var/log/chrome
      chmod 777 /var/log/chrome
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
      - key: PATH
        value: "/usr/local/bin:/usr/bin:${PATH}"
      - key: TMPDIR
        value: "/tmp"
      - key: CHROME_USER_DATA_DIR
        value: "/tmp/.chrome"
      - key: CHROME_LOG_FILE
        value: "/var/log/chrome/chrome.log"
    healthCheckPath: /health
    autoDeploy: true 