services:
  - type: web
    name: apple-tv-bot
    env: python
    buildCommand: |
      # Add Google Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      
      # Update package list and install Chrome
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Install ChromeDriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
      curl -Lo /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip -q /tmp/chromedriver.zip -d /usr/bin/
      chmod +x /usr/bin/chromedriver
      rm /tmp/chromedriver.zip
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RENDER
        value: "true"
    healthCheckPath: /health
    autoDeploy: true 